# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Touma Kazusa"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/my_logo2.jpg"

logo2: "/assets/images/logo4.jpg"
# blog cover
cover: "/assets/images/cover2.jpg"

name: 'Dirk Fabisch'
author: 'Dirk Fabisch'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.touma-kazusa.com" # the base hostname & protocol for your site
baseurl: 

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dirkfabisch
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dirkfabisch
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
